### ISSUE TITLE
Trying to open wrong file

### ISSUE THREAD

**Issue by MysticRyuujin** [jpgxs/python-sadf#6]
code:
```
import sadf
from sadf import fieldgroups as fg
cmd = sadf.SadfCommand()
cmd.field_groups = [ fg.Network(dev=True) ]
report = cmd.run()
```

Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/sadf/__init__.py", line 141, in run
    results = self._exec()
  File "/usr/local/lib/python3.8/dist-packages/sadf/__init__.py", line 238, in _exec
    raise SadfCommandException('Failed to execute sadf command: {}'
sadf.SadfCommandException: Failed to execute sadf command: Cannot open /var/log/sysstat/sa13: No such file or directory
Please check if data collecting is enabled
```

/var/log/sysstat:
```
$ ls -al /var/log/sysstat
total 324
drwxr-xr-x  2 root root     4096 Jul 12 08:35 .
drwxrwxr-x 10 root syslog   4096 Jul 12 20:24 ..
-rw-r--r--  1 root root   316812 Jul 12 20:25 sa12
```

Looking for sa13?

**Comment by MysticRyuujin** [comment]
I assume this is timzeone related? The server is set to CDT...which it's currently the 12th, but UTC it's the 13th... Not sure how to fix though.
